//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycongviec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class congviec
    {
        public int id { get; set; }
        public string workname { get; set; }
        public Nullable<System.DateTime> startday { get; set; }
        public Nullable<System.DateTime> endday { get; set; }
        public Nullable<int> nhanvien_name { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
